### ISSUE TITLE
Configure coordinates precision

### ISSUE THREAD

**Issue by pavelsimo** [vahancho/polylineencoder#5]
Hi, 

Would it be possible to have precision as a parameter for the methods `encode()` and `decode()`?

For example:
https://github.com/hicsail/polyline/blob/master/polyline/codec.py#L39

For map data 6 digits precision is quite common:
https://en.wikipedia.org/wiki/Decimal_degrees#Precision

BTW, I could create a merge request, please let me know.

Thanks,
Pavel

**Comment by vahancho** [comment]
Hi,

According to the [algorithm description](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) it assumes  a precision of 5 decimal places. Can you bring an example, where precision matters? I will appreciate a test case that demonstrates the issue.

Thanks.
Vahan

**Comment by pavelsimo** [comment]
Hi,

Thank you so much for the quick reply! 

Yes, you're right, the google polyline algorithm does not mention anything about 6 digits precision, but some map data (e.g. [OSM](https://help.openstreetmap.org/questions/7307/how-precise-can-osm-get)), do have cm accuracy, and for some use cases such as precise localization this accuracy is important.

As an example, you can have a look at pretty much all Valhalla APIs (search for the keyword "polyline"):

- [Valhalla Elevation Service](https://valhalla.readthedocs.io/en/latest/api/elevation/api-reference/)
- [Valhalla Routing Service](https://valhalla.readthedocs.io/en/latest/api/turn-by-turn/api-reference/)

Valhalla APIs provide polyline with either 5-digit or 6-digit precision, for the 6-digit precision your library won't be able to decode them correctly since precision always defaults to 5-digits, and cannot be adjusted by a client without changing the source code. 

Thanks,
Pavel

**Comment by vahancho** [comment]
Hi Pavel,

Thank you for details. I have several points that speak rather against making the precision configurable. Here they are:
- The library is designed to strictly conform Google Encoded Polyline Algorithm Format algorithm. It's not guarantied that that the library will correctly decode strings that encoded by other libraries;
- Precision of more than five decimal digits hardly make sense as there are no such maps with centimeters precision. At least, I never so such a real world map,
- Increasing precision not always lead to increasing the accuracy,
- Having configurable precision may lead to errors, because coordinate may be encoded with one precision and decoded with another. The encoded strings don't contain information about the precision.

Thus I prefer to preserve the current approach and use the constant precision of five decimal places, as specified.

**Comment by pavelsimo** [comment]
Hi Vahan,

Just a few remark to your points:

- You could always default to 5-digits precision, thus strictly conform to the google specification (e.g. `encode=5`).
- There are maps with centimeters precision, please have a look at [HD Maps](https://www.here.com/platform/automotive-services/hd-maps), data collection for those maps is done with Lidar sensors, and differential GPS.
- True, depends on the data
- The client should be aware of the polyline is trying to encode/decode, I do agree is not ideal, and should be part of the format.

Anyways, thank you for taking the time to reply.

Best regards,
Pavel

**Comment by vahancho** [comment]
Hi Pavel,

Thank you for more details. They make sense. I decided to reopen this issue to work on.

Cheers,
Vahan

**Comment by pavelsimo** [comment]
Awesome, thanks! 😄
